version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: pass1234
      DB_NAME: funapp
      JWT_SECRET: shezlong
      PORT: 3000
    depends_on:
      - db

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass1234
      MYSQL_DATABASE: funapp
    ports:
      - '3307:3306'
